### ISSUE TITLE
Feature: Expand amount of entries in the statistics page

### ISSUE THREAD

**Issue by h3oCharles** [AdmiralGT/botc-scripts#333]
**Description**
A clear and concise description of what feature you'd like to see. Please provide as much detail as possible. 

some way to see more than just top/bottom 5 of the characters, top 15 at the very least
perhaps a button below the list of 5 that shows an additional 10 choices

**Additional context**

I've made a script that consists of the most picked characters according to the statistics page (with a couple of personal changes)
https://botc-scripts.azurewebsites.net/script/1998
the difficulty I had with creating this script is with picking townsfolk - the page only displays 5 of them, whereas ideally in a full script, there should be 13, so I had to do some weird Excel trickery akin to Venn diagrams

I'm thinking of doing this kind of exercise monthly-ish, to see how characters trend over time <-- perhaps that could be automatable and as a separate issue

**Comment by AdmiralGT** [comment]
Thanks for the ticket. It's actually already possible to see more than the top/bottom 5 on the statistics page but this isn't well advertised so I apologise that you had to try and work around this! You can set the number though by providing the `num` parameter to the statistics page e.g. https://botc-scripts.azurewebsites.net/statistics?num=20

I've never yet got round to improving the UI for this experience since sliders require jQuery and I try to avoid that where possible. 

I'd exercise a word of caution though on the monthly updates, I don't think there's much change in the most popular roles with only some fringe changes. I have thought about auto-generating the most/least popular character scripts so that it doesn't get included in the statistics page (since created scripts will just self perpetuate.

It may be interesting though to generate a graph of each roles popularity over time, I'll add the UI update and Graph to the backlog.

**Comment by AdmiralGT** [comment]
I've added a slider! https://github.com/AdmiralGT/botc-scripts/pull/431
