### ISSUE TITLE
Bug: New Script Format Not Supported

### ISSUE THREAD

**Issue by tseel** [AdmiralGT/botc-scripts#425]
**Describe the bug**
The script format has changed so that ids for characters with multiple words in their name no longer have an underscore. For example, the Fortune Teller used to be `fortune_teller` and is now `fortuneteller`.

These characters are not showing up properly in the character list.

**To Reproduce**
Is this problem reproduceable, if so, please provide the steps required to reproduce the behavior:
1. Go to any recently created script which has characters with multiple words: for example [Dogma by Luxray](https://botcscripts.com/script/4167/1.0.2)
2. Go to the Characters tab
3. See that in the character list, several characters have black text and their new IDs, instead of color based on character type and their character name.

**Screenshots**
![image](https://github.com/user-attachments/assets/598db732-8e7b-4f24-945b-228f874ced0b)

**Comment by tseel** [comment]
Looks like this will be a database update, should support both IDs to not break old scripts.

Alternatively, could ignore underscores in IDs all together (this is what bra1n has said the official app does - have not confirmed myself lol)

**Comment by AdmiralGT** [comment]
Thanks for the report. I was completely unaware of this change. I know both formats have been valid for a while and I was mostly ignoring the problem as the format of the existing characters didn't change so it was only really an issue when people manually hacked them in some way (usually when a new character was released an not officially supported).

It's not possible to simply ignore underscores since all the existing JSONs are stored with the original IDs and so things like search won't just work without a mapping backwards to the originals (something has to know that if you search for `scarletwoman` or `scarlet_woman` actually means searching for `scarletwoman` and `scarlet_woman`.

That's what I originally proposed for the [`mephit` issue](https://github.com/AdmiralGT/botc-scripts/issues/174) but I ultimately cheapened out and just changed `mephit` to `mezepheles` everywhere. That's likely harder to do now as there are so many more scripts to search through and update but there's really not a great format for storing "this character can be one of n IDs". Likely may just have to be some downtime while I hammer the update.

It'll probably be a few days until this gets resolved. It's not really causing any harm from a functionality perspective beyond search by character and just cause general ugliness.

**Comment by AdmiralGT** [comment]
I have migrated the database to remove special characters and now character usage everywhere is without special characters.
