### ISSUE TITLE
Bug:I am trying to view my collection and getting Error 500. All other collections seem OK.

### ISSUE THREAD

**Issue by jjellinek** [AdmiralGT/botc-scripts#465]
**Describe the bug**
When logged in and clicking on my collection: https://botcscripts.com/collection/32 I get an Error 500. All other collections seem fine.

**When did it happen**
I think this started to happen since the last update.

**To Reproduce**
1. Go to https://botcscripts.com/collection/32
2. See error

**Browser details:**

Google Chrome | 130.0.6723.70 (Official Build) (64-bit) (cohort: Stable)
Revision | 4d304ce63c47778289663b251c8382526640c9a0-refs/branch-heads/6723@{#1453}
OS | Windows 11 Version 23H2 (Build 22631.4169)
JavaScript | V8 13.0.245.18
User agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Command Line | "C:\Program Files\Google\Chrome\Application\chrome.exe" --restart --flag-switches-begin --flag-switches-end

**Comment by jjellinek** [comment]
So this only happens when I'm logged in, and it is my own collection.

**Comment by AdmiralGT** [comment]
Thanks for reporting the issue. Looks like I have screwed up the inheritance structure on Collection tables which has resulted in the CollectionClocktowerTable which is used when you are trying to view your own collection being broken.

I should be able to deploy a fix within the next 12 hours.

Notes for myself:
`CollectionClocktowerTable` is trying to display a `scripts_in_collection` column which doesn't exist in its inheritance model because it never includes a `CollectionTable`. Not quite sure why this got separated out with a weird structure, should probably be merged back into a single class.

**Comment by AdmiralGT** [comment]
I believe this is now fixed.

**Comment by jjellinek** [comment]
Works for me now thanks.
