### ISSUE TITLE
Bug: Scripts with Homebrew characters appear as character changes in the History tab even if they don't change

### ISSUE THREAD

**Issue by GrayPockets** [AdmiralGT/botc-scripts#472]
**Describe the bug**
When uploading new versions of a script with homebrew characters, and the homebrew characters don't change, they still show as a character change on the history page.

**When did it happen**
4:30 AM PST on 11/5/2024

**To Reproduce**
Is this problem reproduceable, if so, please provide the steps required to reproduce the behavior:
1. Go to https://botc-scripts.azurewebsites.net/
2. Click on Upload
3. Upload a script with homebrew characters
4. Click "Upload a new version" and upload the script with minor changes, but nothing to the homebrew characters
5. Click History
6. See that the homebrew characters look like they have changed.

**Screenshots**
![image](https://github.com/user-attachments/assets/a21437c9-efee-435d-9ef6-1623cafe75f0)

**Additional context**
Add any other context about the problem here e.g. the JSON/PDF of the script
[Delirium Promenade.json 3.0.1](https://github.com/user-attachments/files/17632549/Delirium.Promenade.json)
[Delirium Promenade.json 3.0.2](https://github.com/user-attachments/files/17632552/Delirium.Promenade.json)

**Comment by AdmiralGT** [comment]
Thanks for reporting, this function was never really intended for hybrid scripts but I have implemented some changes here. Sadly this is never going to be perfect, if you replace the official Lycanthrope character with your own character called Lycanthrope then it will appear as Lycanthrope being added and removed. When this checking occurs it just uses the data in the JSON (rather than comparing to any official character) and so it just doesn't know what that should look like. 

There is a new display though for characters that have changed ability, but again that won't cope with a character changing name or ID to represent the same thing. That's just not something expected to happen.

**Comment by GrayPockets** [comment]
It works perfectly from my perspective now. Thank you.

I did expect it to update when I changed from "lycanthrope" to "lycanthrope_dp", so that's perfect! Thank you so much!
